version: "3.9"
services:
  api:
    build: ./
    ports:
      - "8082:8080"
#    depends_on:
#      - database
#  database:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: password