# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on: [push]

env:
  REPO_NAME: spring-playground

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        run: mvn -B package --file pom.xml -Dmaven.test.skip

      - name: Docker build
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: docker build -t "$DOCKER_USER"/"$REPO_NAME":latest .

      - name: Docker publish
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_TOKEN:  ${{ secrets.DOCKER_TOKEN }}
        run: |
          echo "$DOCKER_TOKEN"|docker login -u "$DOCKER_USER" --password-stdin
          docker push "$DOCKER_USER"/"$REPO_NAME":latest
